//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_NF_crud.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public long pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_description { get; set; }
        public Nullable<decimal> pro_price { get; set; }
        public Nullable<int> pro_active { get; set; }
        public Nullable<int> pro_cate_id { get; set; }
        public string pro_image { get; set; }
    
        public virtual tbl_category tbl_category { get; set; }
    }
}
